# tasks file for fail2ban
---
- include: package.yml
  when: fail2ban_install == 'package'

- include: source.yml
  when: fail2ban_install == 'source'

- name: update configuration file - /etc/fail2ban/fail2ban.conf
  template:
    src: etc/fail2ban/fail2ban.conf.j2
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]

- name: setup filters
  template:
    src: filter.conf.j2
    dest: /etc/fail2ban/filter.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]
  with_items: "{{fail2ban_filters}}"
  when: fail2ban_filters

- name: setup actions
  template:
    src: action.conf.j2
    dest: /etc/fail2ban/action.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]
  with_items: "{{fail2ban_actions}}"
  when: fail2ban_actions

- name: setup jails
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: [configuration, fail2ban, fail2ban-configuration]
  with_items: "{{fail2ban_jails}}"
  when: fail2ban_jails

- name: check if fail2ban is up
  command: fail2ban-client ping 2> /dev/null
  register: result
  ignore_errors: yes

- name: start service
  command: fail2ban-client start
  when: "'Failed' in result.stderr"
