---
- name: install
  apt:
    name: fail2ban
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags: [configuration, fail2ban, fail2ban-install]  
